version: '3.8'

services:
  och-ai:
    build: 
      context: .
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
        - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
        - VITE_GA_TRACKING_ID=${VITE_GA_TRACKING_ID}
    ports:
      - "5173:4173"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_GA_TRACKING_ID=${VITE_GA_TRACKING_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Enhanced security options for production
    security_opt:
      - no-new-privileges:true
    read_only: true  # Read-only filesystem
    tmpfs:
      - /tmp
      - /var/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
