version: '3.8'

services:
  och-ai-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_GA_TRACKING_ID=${VITE_GA_TRACKING_ID}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0