name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run TypeScript check
      run: npm run type-check
    
    - name: Build application
      run: npm run build
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # 添加错误处理，如果ssh-keyscan失败则跳过
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || echo "SSH keyscan failed, continuing..."
    
    - name: Deploy to Production
      run: |
        echo "Connecting to server..."
        echo "User: ${{ secrets.SERVER_USER }}"
        echo "Host: ${{ secrets.SERVER_HOST }}"
        echo "Port: ${{ secrets.SERVER_PORT || '22' }}"
        echo "Secrets configured successfully!"
        
        if [ -z "${{ secrets.SERVER_USER }}" ] || [ -z "${{ secrets.SERVER_HOST }}" ]; then
          echo "Error: SERVER_USER or SERVER_HOST secrets are not set"
          exit 1
        fi
        
        # 构建SSH命令，支持自定义端口
        SSH_PORT="${{ secrets.SERVER_PORT || '22' }}"
        SSH_CMD="ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}"
        
        echo "SSH Command: $SSH_CMD"
        
        $SSH_CMD "
          cd /root/och &&
          git pull origin main &&
          docker compose down &&
          docker compose build --no-cache &&
          docker compose up -d
        "
    
    - name: Health Check
      run: |
        sleep 30
        curl -f http://${{ secrets.SERVER_HOST }}:5173/ || exit 1
